import type { Metadata } from "next";
import { Rubik, Lato, Roboto } from "next/font/google";
import "./globals.scss";

const rubik = Rubik({
  weight: ["400", "800", "700"],
  variable: "--font-rubik",
  subsets: ["latin"],
});

const lato = Lato({
  weight: ["400", "700", "900"],
  variable: "--font-lato",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: ["200", "400", "600"],
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} ${lato.variable} ${roboto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
